# Declare global configurations
global:
  kibanaEnabled: false

############### Kafka and Zookeeper ####################
## Reference: https://github.com/bitnami/charts/blob/main/bitnami/kafka/values.yaml
kafka:
  enabled: true
  fullnameOverride: "kafka"

  persistence:
    enabled: false

  ## https://github.com/bitnami/charts/blob/main/bitnami/zookeeper/values.yaml
  zookeeper:
    persistence:
      enabled: true

    fullnameOverride: "zookeeper"

  ## Kafka provisioning
  provisioning:
    enabled: true
    numPartitions: 1
    replicationFactor: 1

    topics:
    - name: KAFKA_AUDITS_TOPIC
      value: audits
    - name: KAFKA_LOGS_TOPIC
      value: logs
    - name: AccountLookupBcRequests
      value: AccountLookupBcRequests
    - name: AccountLookupBcEvents
      value: AccountLookupBcEvents
    - name: AccountLookupBcResponses
      value: AccountLookupBcResponses
    - name: AccountLookupBcErrors
      value: AccountLookupBcErrors
    - name: OperatorBcErrors
      value: OperatorBcErrors
    - name: QuotingBcErrors
      value: QuotingBcErrors
    - name: QuotingBcEvents
      value: QuotingBcEvents
    - name: QuotingBcRequests
      value: QuotingBcRequests
    - name: SettlementsBcRequests
      value: SettlementsBcRequests
    - name: TransfersBcErrors
      value: TransfersBcErrors
    - name: TransfersBcTimeouts
      value: TransfersBcTimeouts
    - name: TransfersBcEvents
      value: TransfersBcEvents
    - name: TransfersBcRequests
      value: TransfersBcRequests
    - name: SettlementsBcEvents
      value: SettlementsBcEvents
    - name: SettlementsBcCommands
      value: SettlementsBcCommands
    - name: PlatformConfigurationBcEvents
      value: PlatformConfigurationBcEvents

    nodeSelector: {}
    tolerations: []
    waitForKafka: true

############### RedPanda Console for Kafka  ####################
# https://artifacthub.io/packages/helm/redpanda-data/console?modal=values
# redpanda kakfa console config

redpanda-console:
  enabled: true
  fullnameOverride: rpconsole

  console:
    config:
      kafka:
        brokers:
          - kafka:9092

  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: redpanda-console.local
        paths:
          - path: /
            pathType: ImplementationSpecific

############### MongoDB  ####################
# https://github.com/bitnami/charts/tree/main/bitnami/mongodb
mongodb:
  enabled: true
  image:
    tag: 5.0.18-debian-11-r8

  fullnameOverride: "mongodb"
  auth:
    enabled: true

    rootUser: root
    rootPassword: mongoDbPas42
    usernames:
    - 'mojaloop'
    passwords:
    - 'password'
    databases:
    - 'mlos'

    replicaSetKey: ""
    existingSecret: ""
  persistence:
    enabled: false

############### Mongo Express ####################
# mongo express config
mongo-express:
  fullnameOverride: mongo-express
  enabled: true

  ingress:
    enabled: true
    ingressClassName: nginx

  mongodbEnableAdmin: true
  mongodbAdminPassword: mongoDbPas42

############### Redis  ####################
## Reference: https://github.com/bitnami/charts/blob/main/bitnami/redis/values.yaml
redis:
  enabled: true
  fullnameOverride: redis
  architecture: standalone
  auth:
    enabled: false
  master:
    disableCommands: []
    persistence:
      enabled: false

############### Elasticsearch and Kibana  ####################
elasticsearch:
  enabled: false
  # fullnameOverride: "elastic"

  security:
    elasticPassword: elasticSearchPas42
    tls:
      restEncryption: false

  coordinating:
    replicaCount: 1

  master:
    replicaCount: 1
    persistence:
      enabled: false

  data:
    replicaCount: 1
    persistence:
      enabled: false

  ingest:
    replicaCount: 1

  ingress:
    enabled: true
    # hostname: es01
