apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose-apps.yml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: accounts-and-balances-coa-grpc-svc
  name: accounts-and-balances-coa-grpc-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: accounts-and-balances-coa-grpc-svc
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose-apps.yml convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: accounts-and-balances-coa-grpc-svc
    spec:
      containers:
        - env:
            - name: AUTH_N_SVC_BASEURL
              value: http://authentication-svc:3201
            - name: AUTH_N_TOKEN_AUDIENCE
              value: mojaloop.vnext.dev.default_audience
            - name: AUTH_N_TOKEN_ISSUER_NAME
              value: mojaloop.vnext.dev.default_issuer
            - name: AUTH_Z_SVC_BASEURL
              value: http://authorization-svc:3202
            - name: BUILTIN_LEDGER_SVC_URL
              value: accounts_and_balances_builtin-ledger-grpc-svc:3350
            - name: KAFKA_AUDITS_TOPIC
              value: audits
            - name: KAFKA_LOGS_TOPIC
              value: logs
            - name: KAFKA_URL
              value: kafka:19092
            - name: MONGO_URL
              value: mongodb://root:mongoDbPas42@mongo:27017/
            - name: PLATFORM_CONFIG_BASE_SVC_URL
              value: http://platform-configuration-svc:3100
            - name: TIGERBEETLE_CLUSTER_ID
              value: "0"
            - name: TIGERBEETLE_CLUSTER_REPLICA_ADDRESSES
              value: tigerbeetle:3000
          image: mojaloop/accounts-and-balances-bc-coa-grpc-svc:alpha-latest
          livenessProbe:
            exec:
              command:
                - nc -z localhost 3300 || exit -1
            failureThreshold: 10
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
          name: accounts-and-balances-coa-grpc-svc
          ports:
            - containerPort: 3300
          resources: {}
          volumeMounts:
            - mountPath: /app/data
              name: aandb-coa-grpc-svc-data
      restartPolicy: Always
      volumes:
        - name: aandb-coa-grpc-svc-data
          persistentVolumeClaim:
            claimName: aandb-coa-grpc-svc-data
status: {}
