apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose-apps.yml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: quoting-svc
  name: quoting-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: quoting-svc
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose-apps.yml convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: quoting-svc
    spec:
      containers:
        - env:
            - name: AUTH_N_SVC_BASEURL
              value: http://authentication-svc:3201
            - name: AUTH_N_TOKEN_AUDIENCE
              value: mojaloop.vnext.dev.default_audience
            - name: AUTH_N_TOKEN_ISSUER_NAME
              value: mojaloop.vnext.dev.default_issuer
            - name: AUTH_Z_SVC_BASEURL
              value: http://authorization-svc:3202
            - name: KAFKA_AUDITS_TOPIC
              value: audits
            - name: KAFKA_LOGS_TOPIC
              value: logs
            - name: KAFKA_URL
              value: kafka:19092
            - name: MONGO_URL
              value: mongodb://root:mongoDbPas42@mongo:27017/
            - name: PARTICIPANTS_SVC_URL
              value: http://participants-svc:3010
            - name: PLATFORM_CONFIG_BASE_SVC_URL
              value: http://platform-configuration-svc:3100
          image: mojaloop/quoting-bc-quoting-svc:alpha-latest
          livenessProbe:
            exec:
              command:
                - nc -z localhost 3033 || exit -1
            failureThreshold: 10
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
          name: quoting-svc
          ports:
            - containerPort: 3033
          resources: {}
          volumeMounts:
            - mountPath: /app/data
              name: quoting-svc-data
      restartPolicy: Always
      volumes:
        - name: quoting-svc-data
          persistentVolumeClaim:
            claimName: quoting-svc-data
status: {}
