apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    mojaloop.service: authentication-svc
  name: authentication-svc
spec:
  ports:
    - name: "3201"
      port: 3201
      targetPort: 3201
  selector:
    mojaloop.service: authentication-svc
status:
  loadBalancer: {}
