apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  creationTimestamp: null
  labels:
    mojaloop.service: authorization-svc
    mojaloop.layer: crosscut
  name: authorization-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      mojaloop.service: authorization-svc
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      creationTimestamp: null
      labels:
        mojaloop.service: authorization-svc
        mojaloop.layer: crosscut
    spec:
      containers:
        - env:
            - name: KAFKA_AUDITS_TOPIC
              value: audits
            - name: KAFKA_LOGS_TOPIC
              value: logs
            - name: KAFKA_URL
              value: kafka:9092
            - name: PLATFORM_CONFIG_BASE_SVC_URL
              value: http://platform-configuration-svc:3100
          image: mojaloop/security-bc-authorization-svc:0.1.19
          name: authorization-svc
          ports:
            - containerPort: 3202
          resources: {}
          volumeMounts:
            - mountPath: /app/data
              name: authorization-svc-data
      restartPolicy: Always
      volumes:
        - name: authorization-svc-data
          persistentVolumeClaim:
            claimName: authorization-svc-data
status: {}
