apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    mojaloop.service: ttk-2
  name: ttk-2
spec:
  ports:
    - name: "4041"
      port: 4041
      targetPort: 4040
    - name: "5051"
      port: 5051
      targetPort: 5050
  selector:
    mojaloop.service: ttk-2
status:
  loadBalancer: {}
